export const FETCH_WIKI_START     = 'FETCH_WIKI_START';
export const FETCH_WIKI_SUCCESS   = 'FETCH_WIKI_SUCCESS';
export const FETCH_WIKI_FAILURE   = 'FETCH_WIKI_FAILURE';
export const FETCH_GOOGLE_START   = 'FETCH_GOOGLE_START';
export const FETCH_GOOGLE_SUCCESS = 'FETCH_GOOGLE_SUCCESS';
export const FETCH_GOOGLE_FAILURE = 'FETCH_GOOGLE_FAILURE';
export const SET_SEARCH_QUERY     = 'SET_SEARCH_QUERY';
